[Deployment]
# SharePoint deployment path
sharepoint_path=C:\Users\sesa51816\Schneider Electric\SG Control & Signaling Group - Documents\General\Other Python tools

# Name users will see on SharePoint
deploy_name=Quick Notes.exe

# Your contact email for README
contact_email=didier.severac@se.com

# Spec file (auto-detected if blank)
spec_file=quick_notes.onefile.spec

# Project directory (leave blank to use script location)
project_dir=

[VirtualEnvironment]
# Virtual environment root directory
venv_root=C:\PythonProjects\Venv

# Virtual environment name
venv_name=Python313

# OR use a relative path from project:
# venv_path=venv.
deploy_mode=pyinstaller
